# Generated by Django 5.0.7 on 2024-07-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=10)),
                ('courseTitle', models.CharField(max_length=30)),
                ('courseCredits', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='student_set', to='helloApp.course'),
        ),
    ]
